import os, math, argparse
import numpy as np
import torch
from plyfile import PlyData, PlyElement

# ---------- helper: read PLY vertex to numpy structured ----------
def read_ply(path):
    ply = PlyData.read(path)
    v = ply['vertex'].data
    return v

def write_ply(path, v_np):
    el = PlyElement.describe(v_np, 'vertex')
    PlyData([el], text=False, byte_order='<').write(path)

def get_fields(v):
    return v.dtype.names

# ---------- build DC/opacity tables aligned to PS1 using index layers ----------
def build_tables(ps1_v, layer_paths):
    """
    ps1_v: structured np array for PS1, length N
    layer_paths: list of (layer_id, ply_path_with_index) for layers 1..L-1
    Returns:
      shs_dcs: np float32 [N, L, 3]
      opac:   np float32 [N, L]
    """
    N = len(ps1_v)
    # fields exist in PS1
    shs_dcs = np.zeros((N, L, 3), dtype=np.float32)
    opac = np.ones((N, L), dtype=np.float32)

    # layer0 from PS1
    shs_dcs[:,0,0] = ps1_v['f_dc_0'].astype(np.float32)
    shs_dcs[:,0,1] = ps1_v['f_dc_1'].astype(np.float32)
    shs_dcs[:,0,2] = ps1_v['f_dc_2'].astype(np.float32)
    opac[:,0] = ps1_v['opacity'].astype(np.float32)

    # propagate
    for li in range(1, L):
        shs_dcs[:,li,:] = shs_dcs[:,li-1,:]
        opac[:,li] = opac[:,li-1]

    # overlay from each coarse ply using its index field
    for li, p in layer_paths:
        v = read_ply(p)
        if 'index' not in v.dtype.names:
            raise RuntimeError(f"{p} has no 'index' field (need index-version ply).")
        idx = v['index'].astype(np.int64)
        # update DC + opacity for those points at layer li
        shs_dcs[idx, li, 0] = v['f_dc_0'].astype(np.float32)
        shs_dcs[idx, li, 1] = v['f_dc_1'].astype(np.float32)
        shs_dcs[idx, li, 2] = v['f_dc_2'].astype(np.float32)
        opac[idx, li] = v['opacity'].astype(np.float32)

    return shs_dcs, opac

# ---------- project 3D points to screen uv using a reference camera ----------
def load_first_test_camera(scene_root):
    """
    Read cameras.json generated by training (ms_d_ft etc).
    For your dataset folders, cameras.json is usually under some output trial.
    But for simplicity we read the standard 3DGS-style transforms.json is not available here.
    So we do a fallback: use COLMAP camera params from the dataset folder used by Fov-3DGS.
    If you already have cameras.json in the trial you evaluate, pass it explicitly.
    """
    raise RuntimeError("Need camera file path. Please pass --cameras_json pointing to cameras.json (the one already in your trial output).")

def load_cameras_json(path):
    import json
    with open(path, "r") as f:
        data = json.load(f)

    cam = data[0] if isinstance(data, list) else (data["cameras"][0] if isinstance(data, dict) and "cameras" in data else data)

    # expected keys in your cameras.json: width, height, position, rotation, fx, fy
    W = int(cam["width"])
    H = int(cam["height"])
    fx = float(cam["fx"])
    fy = float(cam["fy"])

    # principal point (assume centered)
    cx = (W - 1) * 0.5
    cy = (H - 1) * 0.5

    # camera center in world
    C = np.array(cam["position"], dtype=np.float32).reshape(3)

    # rotation: assume a 3x3 matrix (row-major) that maps camera->world
    R = np.array(cam["rotation"], dtype=np.float32).reshape(3,3)

    return W, H, fx, fy, cx, cy, R, C


def project_uv(xyz, R, C, fx, fy, cx, cy, W, H):
    # world -> camera: Xc = R^T (X - C)   (R is camera->world)
    X = xyz.astype(np.float32)
    Xc = (X - C[None, :]) @ R  # (N,3) because (X-C) * (camera->world)?? we need R^T; so use @R.T if R is camera->world.
    # Correction: if R is camera->world, then world->camera is R^T
    Xc = (X - C[None, :]) @ R.T

    z = Xc[:, 2]
    valid = z > 1e-6

    u = fx * (Xc[:, 0] / np.maximum(z, 1e-6)) + cx
    v = fy * (Xc[:, 1] / np.maximum(z, 1e-6)) + cy

    # convert to 0..1 uv, and flip v to match screen-space convention
    uu = (u / max(W-1, 1)) 
    vv = 1.0 - (v / max(H-1, 1))

    uv = np.stack([uu, vv], axis=1).astype(np.float32)
    # also require inside screen
    valid = valid & (uu >= 0) & (uu <= 1) & (vv >= 0) & (vv <= 1)
    return uv, valid

# ---------- main ----------
if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--base_folder", required=True, help=".../dataset/bicycle/4_12_0.01_1.0/")
    ap.add_argument("--layer_num", type=int, default=4)
    ap.add_argument("--max_pooling_size", type=int, default=12)
    ap.add_argument("--ps1_iter", type=int, default=55000)
    ap.add_argument("--coarse_iter", type=int, default=7500)
    ap.add_argument("--metric", type=str, default="surface")
    ap.add_argument("--cameras_json", required=True, help="Use the cameras.json from your trial output (e.g., ms_d_ft/cameras.json)")
    # radii in UV distance
    ap.add_argument("--r0", type=float, default=0.12)
    ap.add_argument("--r1", type=float, default=0.22)
    ap.add_argument("--r2", type=float, default=0.35)
    ap.add_argument("--out_dir", default=None)
    args = ap.parse_args()

    L = args.layer_num
    assert L == 4, "This script currently assumes 4 layers."

    # paths
    ps1_ply = os.path.join(args.base_folder, f"1_PS1_{L}_{args.max_pooling_size}", "point_cloud", f"iteration_{args.ps1_iter}", "point_cloud.ply")
    # these are the 3 coarse layers generated by masking; their folder names depend on pooling sizes.
    # We infer them the same way as compose_models.py did:
    sqrt_m = args.max_pooling_size ** 0.5
    interval = (sqrt_m - 1) / (L - 1)
    psizes = []
    for i in range(L):
        pooling = 1 + interval * i
        psizes.append(round(pooling**2))
    # fixed args used in repo scripts
    arg2, arg3 = 6000, 1500
    layer_paths = []
    for li in range(1, L):
        folder = f"{psizes[li]}_{arg2}-{arg3}_{L}_{args.metric}"
        p = os.path.join(args.base_folder, folder, "point_cloud", f"iteration_{args.coarse_iter}", "point_cloud.ply")
        layer_paths.append((li, p))

    print("PS1:", ps1_ply)
    for li,p in layer_paths:
        print("L",li,":",p)

    ps1_v = read_ply(ps1_ply)
    fields = get_fields(ps1_v)
    required = ["x","y","z","f_dc_0","f_dc_1","f_dc_2","opacity","scale_0","scale_1","scale_2","rot_0","rot_1","rot_2","rot_3"]
    for k in required:
        if k not in fields:
            raise RuntimeError(f"PS1 PLY missing field {k}")

    shs_dcs, opac = build_tables(ps1_v, layer_paths)

    # load a reference camera to decide which points lie near gaze in screen space
    W, H, fx, fy, cx, cy, R, C = load_cameras_json(args.cameras_json)
    
    xyz = np.stack([ps1_v['x'], ps1_v['y'], ps1_v['z']], axis=1).astype(np.float32)
    uv, valid = project_uv(xyz, R, C, fx, fy, cx, cy, W, H)
# gaze samples (same 3x3 grid)
    gazes = [(0.25*i, 0.25*j) for i in range(1,4) for j in range(1,4)]

    out_dir = args.out_dir or os.path.join(args.base_folder, f"composed_ply_9gazes_{L}_{args.max_pooling_size}")
    os.makedirs(out_dir, exist_ok=True)

    # prepare base output dtype (Unity-friendly: no index, no nx/ny/nz)
    keep = ["x","y","z","nx","ny","nz",
            "f_dc_0","f_dc_1","f_dc_2"] + \
           [f"f_rest_{i}" for i in range(45)] + \
           ["opacity","scale_0","scale_1","scale_2","rot_0","rot_1","rot_2","rot_3"]

    # Some PS1 ply includes nx/ny/nz; if not, we synthesize zeros.
    has_n = all(k in fields for k in ["nx","ny","nz"])
    for gidx,(gu,gv) in enumerate(gazes):
        gaze = np.array([gu,gv], dtype=np.float32)
        d = np.linalg.norm(uv - gaze[None,:], axis=1)
        # invalid projections are treated as far (use outermost)
        d[~valid] = 1e9

        # decide layer per point by distance (ring-based)
        layer_sel = np.full((len(ps1_v),), 3, dtype=np.int32)
        layer_sel[d < args.r2] = 2
        layer_sel[d < args.r1] = 1
        layer_sel[d < args.r0] = 0

        # build output vertex array (start from PS1 geometry)
        dtype = []
        for k in keep:
            if k in fields and k != "opacity":
                dtype.append((k, ps1_v.dtype.fields[k][0]))
            elif k in ["nx","ny","nz"]:
                dtype.append((k, 'f4'))
            else:
                dtype.append((k, 'f4'))
        out_v = np.empty(len(ps1_v), dtype=dtype)

        # copy everything from PS1 for shared fields
        for k in keep:
            if k in fields and k not in ["f_dc_0","f_dc_1","f_dc_2","opacity"]:
                out_v[k] = ps1_v[k]
            elif k in ["nx","ny","nz"]:
                out_v[k] = ps1_v[k].astype(np.float32) if has_n else 0.0
            elif k.startswith("f_rest_"):
                out_v[k] = ps1_v[k] if k in fields else 0.0

        # overwrite DC + opacity from selected layer tables
        out_v["f_dc_0"] = shs_dcs[np.arange(len(ps1_v)), layer_sel, 0]
        out_v["f_dc_1"] = shs_dcs[np.arange(len(ps1_v)), layer_sel, 1]
        out_v["f_dc_2"] = shs_dcs[np.arange(len(ps1_v)), layer_sel, 2]
        out_v["opacity"] = opac[np.arange(len(ps1_v)), layer_sel]

        out_path = os.path.join(out_dir, f"composed_gaze_{gu:.2f}_{gv:.2f}.ply")
        write_ply(out_path, out_v)
        print("Wrote", out_path)

    print("DONE. Output dir:", out_dir)
PY
